"""make StageOption label nullable

Revision ID: 00539de55546
Revises: 9604f0afac60
Create Date: 2025-12-30 12:37:31.232473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00539de55546'
down_revision: Union[str, Sequence[str], None] = '9604f0afac60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stage_options', 'label',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stage_options', 'label',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
