"""make StageOption text nullable

Revision ID: 0ac878630668
Revises: 00539de55546
Create Date: 2025-12-30 12:42:28.688284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac878630668'
down_revision: Union[str, Sequence[str], None] = '00539de55546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stage_options', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stage_options', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
