"""Add difficulty column to StageQuestion

Revision ID: 61422c9f6854
Revises: ecdd7b0b29f0
Create Date: 2026-01-04 14:21:41.532257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61422c9f6854'
down_revision: Union[str, Sequence[str], None] = 'ecdd7b0b29f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage_questions', sa.Column('difficulty', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stage_questions', 'difficulty')
    # ### end Alembic commands ###
