"""Add negative_marks column to mock_test

Revision ID: 78064ffc7fbe
Revises: e016462c1834
Create Date: 2026-01-20 09:34:37.988884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78064ffc7fbe'
down_revision: Union[str, Sequence[str], None] = 'e016462c1834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mock_test', sa.Column('negative_marks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mock_test', 'negative_marks')
    # ### end Alembic commands ###
