"""Update Question and Option models

Revision ID: 8569295093fd
Revises: 61422c9f6854
Create Date: 2026-01-04 16:35:45.556082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8569295093fd'
down_revision: Union[str, Sequence[str], None] = '61422c9f6854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('chapter', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('question_number', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('has_diagram', sa.Boolean(), nullable=True),
    sa.Column('diagram_description', sa.Text(), nullable=True),
    sa.Column('diagram_position', sa.String(), nullable=True),
    sa.Column('diagram_name', sa.Text(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('ai_answer', sa.String(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_chapter'), 'questions', ['chapter'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_question_number'), 'questions', ['question_number'], unique=False)
    op.create_index(op.f('ix_questions_source'), 'questions', ['source'], unique=False)
    op.create_index(op.f('ix_questions_subject'), 'questions', ['subject'], unique=False)
    op.create_index(op.f('ix_questions_topic'), 'questions', ['topic'], unique=False)
    op.create_index(op.f('ix_questions_year'), 'questions', ['year'], unique=False)
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('has_diagram', sa.Boolean(), nullable=True),
    sa.Column('diagram_description', sa.Text(), nullable=True),
    sa.Column('diagram_name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_options_id'), 'options', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_options_id'), table_name='options')
    op.drop_table('options')
    op.drop_index(op.f('ix_questions_year'), table_name='questions')
    op.drop_index(op.f('ix_questions_topic'), table_name='questions')
    op.drop_index(op.f('ix_questions_subject'), table_name='questions')
    op.drop_index(op.f('ix_questions_source'), table_name='questions')
    op.drop_index(op.f('ix_questions_question_number'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_chapter'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
