"""modify StageQuestion nullable fields and add ai_answer

Revision ID: 9604f0afac60
Revises: f4d721b40459
Create Date: 2025-12-30 12:30:55.612626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9604f0afac60'
down_revision: Union[str, Sequence[str], None] = 'f4d721b40459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage_questions', sa.Column('ai_answer', sa.String(), nullable=True))
    op.alter_column('stage_questions', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stage_questions', 'year',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stage_questions', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stage_questions', 'chapter',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stage_questions', 'topic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stage_questions', 'question_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('stage_questions', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stage_questions', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stage_questions', 'question_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('stage_questions', 'topic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stage_questions', 'chapter',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stage_questions', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stage_questions', 'year',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stage_questions', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('stage_questions', 'ai_answer')
    # ### end Alembic commands ###
