"""add_no_of_questions_and_is_active_to_subjects

Revision ID: df9a09756ae3
Revises: eb0fc38f0e39
Create Date: 2026-01-12 11:22:44.661967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9a09756ae3'
down_revision: Union[str, Sequence[str], None] = 'eb0fc38f0e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('no_of_questions', sa.Integer(), nullable=True))
    op.add_column('chapters', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('subjects', sa.Column('no_of_questions', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('topics', sa.Column('no_of_questions', sa.Integer(), nullable=True))
    op.add_column('topics', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'is_active')
    op.drop_column('topics', 'no_of_questions')
    op.drop_column('subjects', 'is_active')
    op.drop_column('subjects', 'no_of_questions')
    op.drop_column('chapters', 'is_active')
    op.drop_column('chapters', 'no_of_questions')
    # ### end Alembic commands ###
