"""remove_class_name_from_subjects

Revision ID: e016462c1834
Revises: 1a5f3a6b6ec1
Create Date: 2026-01-13 12:11:14.672433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e016462c1834'
down_revision: Union[str, Sequence[str], None] = '1a5f3a6b6ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'class_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('class_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
