"""add_formated_name_to_chapter_and_topic

Revision ID: eb0fc38f0e39
Revises: 8569295093fd
Create Date: 2026-01-06 10:29:09.904360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb0fc38f0e39'
down_revision: Union[str, Sequence[str], None] = '8569295093fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_questions_backup')
    op.add_column('chapters', sa.Column('formated_name', sa.String(), nullable=False))
    op.add_column('topics', sa.Column('formated_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'formated_name')
    op.drop_column('chapters', 'formated_name')
    op.create_table('stage_questions_backup',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chapter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('question_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('has_diagram', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('diagram_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('diagram_position', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('diagram_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('solution', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reviewed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ai_answer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
